version: '3.9'

services:
  anti-brute-force:
    build:
      context: ..
      dockerfile: build/Dockerfile
    environment:
      LISTEN_ADDRESS: ":8081"
    ports:
      - "8081:8081"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1G