// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockListService creates a new instance of MockListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListService {
	mock := &MockListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListService is an autogenerated mock type for the ListService type
type MockListService struct {
	mock.Mock
}

type MockListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListService) EXPECT() *MockListService_Expecter {
	return &MockListService_Expecter{mock: &_m.Mock}
}

// IsIPContains provides a mock function for the type MockListService
func (_mock *MockListService) IsIPContains(ip string) (bool, error) {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for IsIPContains")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(ip)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListService_IsIPContains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsIPContains'
type MockListService_IsIPContains_Call struct {
	*mock.Call
}

// IsIPContains is a helper method to define mock.On call
//   - ip string
func (_e *MockListService_Expecter) IsIPContains(ip interface{}) *MockListService_IsIPContains_Call {
	return &MockListService_IsIPContains_Call{Call: _e.mock.On("IsIPContains", ip)}
}

func (_c *MockListService_IsIPContains_Call) Run(run func(ip string)) *MockListService_IsIPContains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListService_IsIPContains_Call) Return(b bool, err error) *MockListService_IsIPContains_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockListService_IsIPContains_Call) RunAndReturn(run func(ip string) (bool, error)) *MockListService_IsIPContains_Call {
	_c.Call.Return(run)
	return _c
}
